import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
	const data = {
		headline: '',
	};

	return (
		<>
			<Head>
				<title>Enhanced</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='max-w-screen-2xl md:h-screen px-4 md:px-8 mx-auto'>
				<header className='flex justify-between items-center py-4 mb-8 md:mb-12 xl:mb-16'>
					<Link
						href='/'
						className='inline-flex items-center text-black-800 text-2xl md:text-3xl font-bold gap-2.5'
						aria-label='logo'
					>
						<svg
							width='95'
							height='94'
							viewBox='0 0 95 94'
							className='w-6 h-auto text-blue-500'
							fill='currentColor'
							xmlns='http://www.w3.org/2000/svg'
						>
							<path d='M96 0V47L48 94H0V47L48 0H96Z' />
						</svg>
						Enhanced
					</Link>

					<nav className='hidden lg:flex items-center gap-8'>
						<Link href='/' className='text-blue-500  font-semibold'>
							Home
						</Link>
						<a
							href='#'
							className='text-gray-600 hover:text-blue-500 active:text-blue-700  font-semibold transition duration-100'
						>
							Features
						</a>
						<a
							href='#'
							className='text-gray-600 hover:text-blue-500 active:text-blue-700  font-semibold transition duration-100'
						>
							Pricing
						</a>
						<a
							href='#'
							className='text-gray-600 hover:text-blue-500 active:text-blue-700  font-semibold transition duration-100'
						>
							About
						</a>
						<a
							href='#'
							className='hidden lg:inline-block bg-blue-500 text-white hover:bg-gray-300 focus-visible:ring ring-blue-300  active:text-gray-700 text-sm md:text-base font-semibold text-center rounded outline-none transition duration-100 px-6 py-3'
						>
							Contact Sales
						</a>
					</nav>

					<button
						type='button'
						className='inline-flex items-center lg:hidden bg-gray-200 hover:bg-gray-300 focus-visible:ring ring-blue-300  active:text-gray-700 text-sm md:text-base font-semibold rounded-lg gap-2 px-2.5 py-2'
					>
						<svg
							xmlns='http://www.w3.org/2000/svg'
							className='h-6 w-6'
							viewBox='0 0 20 20'
							fill='currentColor'
						>
							<path
								fill-rule='evenodd'
								d='M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z'
								clip-rule='evenodd'
							/>
						</svg>
						Menu
					</button>
				</header>

				<section className='flex flex-col lg:flex-row justify-between gap-6 sm:gap-10 md:gap-16'>
					<div className='xl:w-5/12 flex flex-col justify-center sm:text-center lg:text-left lg:py-12 xl:py-24'>
						<h1 className='text-black-800 text-4xl sm:text-4xl md:text-4xl font-bold mb-8'>
							Make your life easier with the help from{' '}
							<span className='text-blue-500'>Enhanced</span>
						</h1>

						<div className='lg:w-4/5 xl:text-lg  mb-8'>
							<ul className='list-inside list-disc'>
								<li>Student Transporting Monitoring</li>
								<li>Intelligent Monitoring System</li>
								<li>Fleet Management</li>
								<li>Smart Cities</li>
							</ul>
						</div>

						<div className='flex flex-col sm:flex-row sm:justify-center lg:justify-start gap-2.5'>
							<a
								href='#'
								className='inline-block bg-blue-500 hover:bg-blue-600 active:bg-blue-700 focus-visible:ring ring-blue-300 text-white text-sm md:text-base font-semibold text-center rounded outline-none transition duration-100 px-8 py-3'
							>
								Start now
							</a>

							<a
								href='#'
								className='inline-block bg-gray-200 hover:bg-gray-300 focus-visible:ring ring-blue-300 text-gray-500 active:text-gray-700 text-sm md:text-base font-semibold text-center rounded outline-none transition duration-100 px-8 py-3'
							>
								Take tour
							</a>
						</div>
					</div>

					<div className='xl:w-5/12 h-48 lg:h-auto bg-gray-100 overflow-hidden shadow-lg rounded-lg'>
						<img
							src='./iot.webp'
							loading='lazy'
							alt='Photo by Fakurian Design'
							className='w-full h-full object-cover object-center'
						/>
					</div>
				</section>
			</div>
			<section className='flex flex-col-reverse md:flex-row max-w-screen-2xl py-4 px-4 md:px-8 mx-auto gap-6 md:gap-8'>
				<div className='xl:w-5/12 h-48 lg:h-auto bg-gray-100 overflow-hidden shadow-lg rounded-lg'>
					<img
						src='./iot.jpg'
						loading='lazy'
						alt='Internet of Things - Enhanced'
						className='w-full h-full object-cover object-center'
					/>
				</div>
				<div className='xl:w-7/12'>
					<p>
						The Internet of Things (IoT) is the network of physical
						objects—devices, vehicles, buildings and other items embedded with
						electronics, software, sensors, and connectivity which enables these
						objects to collect and exchange data. It allows for the seamless
						integration of the digital and physical world to improve efficiency
						and automation.
					</p>
				</div>
			</section>
			<div class='max-w-screen-2xl py-4 px-4 md:px-8 mx-auto'>
				<h2 class='text-gray-800 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-6'>
					Explore the cutting edge of <br />
					<span className='text-blue-600 text-3xl lg:text-4xl'>
						IoT technology
					</span>
				</h2>

				{/* <p class='max-w-screen-md text-gray-500 md:text-lg text-center mx-auto mb-8'>
					This is a section of some simple filler text, also known as
					placeholder text. It shares some characteristics of a real written
					text but is random or otherwise generated.
				</p> */}

				<div class='grid sm:grid-cols-2 md:grid-cols-3 gap-12 xl:gap-16'>
					<div class='flex flex-col items-center'>
						<div class='w-12 md:w-14 h-12 md:h-14 flex justify-center items-center bg-blue-500 text-white rounded-lg md:rounded-xl shadow-lg mb-6'>
							<svg
								xmlns='http://www.w3.org/2000/svg'
								class='w-6 h-6'
								fill='none'
								viewBox='0 0 24 24'
								stroke='currentColor'
							>
								<path
									stroke-linecap='round'
									stroke-linejoin='round'
									stroke-width='2'
									d='M13 7h8m0 0v8m0-8l-8 8-4-4-6 6'
								/>
							</svg>
						</div>

						<h3 class='text-lg md:text-xl font-semibold text-center mb-2'>
							Remote monitoring and control
						</h3>
						<p class='text-gray-500 text-center mb-2'>
							Our IoT solutions feature remote monitoring and control, allowing
							real-time monitoring of devices and systems from any location via
							web portal or mobile app, bringing benefits like energy
							efficiency, cost savings and improved safety.
						</p>
					</div>
					<div class='flex flex-col items-center'>
						<div class='w-12 md:w-14 h-12 md:h-14 flex justify-center items-center bg-blue-500 text-white rounded-lg md:rounded-xl shadow-lg mb-6'>
							<svg
								xmlns='http://www.w3.org/2000/svg'
								class='w-6 h-6'
								fill='none'
								viewBox='0 0 24 24'
								stroke='currentColor'
							>
								<path
									stroke-linecap='round'
									stroke-linejoin='round'
									stroke-width='2'
									d='M13 7h8m0 0v8m0-8l-8 8-4-4-6 6'
								/>
							</svg>
						</div>

						<h3 class='text-lg md:text-xl font-semibold text-center mb-2'>
							Predictive maintenance
						</h3>
						<p class='text-gray-500 text-center mb-2'>
							Predictive maintenance feature in our IoT solutions predict
							potential equipment failures using data analysis, avoiding
							unexpected downtime, improving equipment performance, and
							extending equipment lifespan, which can be accessed remotely.
						</p>
					</div>
					<div class='flex flex-col items-center'>
						<div class='w-12 md:w-14 h-12 md:h-14 flex justify-center items-center bg-blue-500 text-white rounded-lg md:rounded-xl shadow-lg mb-6'>
							<svg
								xmlns='http://www.w3.org/2000/svg'
								class='w-6 h-6'
								fill='none'
								viewBox='0 0 24 24'
								stroke='currentColor'
							>
								<path
									stroke-linecap='round'
									stroke-linejoin='round'
									stroke-width='2'
									d='M13 7h8m0 0v8m0-8l-8 8-4-4-6 6'
								/>
							</svg>
						</div>

						<h3 class='text-lg md:text-xl font-semibold text-center mb-2'>
							Improved security
						</h3>
						<p class='text-gray-500 text-center mb-2'>
							Improved security is a feature of our IoT solutions that ensures
							the protection of sensitive data and systems from unauthorized
							access and malicious attacks.
						</p>
					</div>
				</div>
			</div>
			<section className='flex items-center flex-col-reverse md:flex-row max-w-screen-2xl py-4 px-4 md:px-8 mx-auto gap-6 md:gap-8'>
				<div className='xl:w/12 h-48 lg:h-auto bg-gray-100 overflow-hidden shadow-lg rounded-lg'>
					<img
						src='https://images.unsplash.com/photo-1618004912476-29818d81ae2e?auto=format&q=75&fit=crop&w=1000'
						loading='lazy'
						alt='Photo by Fakurian Design'
						className='w-full h-full object-cover object-center'
					/>
				</div>
				<div>
					<h3 class='text-2xl md:text-3xl font-bold mb-4'>
						Our <span className='text-blue-500'>Vision</span>
					</h3>
					<p className='mb-4'>
						Our vision as an IoT company is to revolutionize people&apos;s lives
						and work through intelligent, connected devices and systems that
						enhance efficiency and improve quality of life. We aim to deliver
						cutting-edge, reliable, secure and easy to use IoT solutions.
					</p>
					<a
						href='#'
						className='inline-block bg-blue-500 hover:bg-blue-600 active:bg-blue-700 focus-visible:ring ring-blue-300 text-white text-sm md:text-base font-semibold text-center rounded outline-none transition duration-100 px-6 py-2'
					>
						Start now
					</a>
				</div>
			</section>
			<section className='bg-blue-400 text-white'>
				<div className='w-10/12 px-4 md:px-8 mx-auto flex flex-wrap items-center justify-between gap-4 py-8'>
					<div className='flex gap-4'>
						<div class='w-12 md:w-14 h-12 md:h-14 flex justify-center items-center bg-white text-blue-500 rounded-lg md:rounded-xl shadow-lg'>
							<svg
								xmlns='http://www.w3.org/2000/svg'
								class='w-6 h-6'
								fill='none'
								viewBox='0 0 24 24'
								stroke='currentColor'
							>
								<path
									stroke-linecap='round'
									stroke-linejoin='round'
									stroke-width='2'
									d='M13 7h8m0 0v8m0-8l-8 8-4-4-6 6'
								/>
							</svg>
						</div>
						<div>
							<h3 className='font-bold text-xl'>+790</h3>
							<p>Happy Clients</p>
						</div>
					</div>
					<div className='flex gap-4'>
						<div class='w-12 md:w-14 h-12 md:h-14 flex justify-center items-center bg-white text-blue-500 rounded-lg md:rounded-xl shadow-lg'>
							<svg
								xmlns='http://www.w3.org/2000/svg'
								class='w-6 h-6'
								fill='none'
								viewBox='0 0 24 24'
								stroke='currentColor'
							>
								<path
									stroke-linecap='round'
									stroke-linejoin='round'
									stroke-width='2'
									d='M13 7h8m0 0v8m0-8l-8 8-4-4-6 6'
								/>
							</svg>
						</div>
						<div>
							<h3 className='font-bold text-xl'>+1200</h3>
							<p>Completed Projects</p>
						</div>
					</div>
					<div className='flex gap-4'>
						<div class='w-12 md:w-14 h-12 md:h-14 flex justify-center items-center bg-white text-blue-500 rounded-lg md:rounded-xl shadow-lg '>
							<svg
								xmlns='http://www.w3.org/2000/svg'
								class='w-6 h-6'
								fill='none'
								viewBox='0 0 24 24'
								stroke='currentColor'
							>
								<path
									stroke-linecap='round'
									stroke-linejoin='round'
									stroke-width='2'
									d='M13 7h8m0 0v8m0-8l-8 8-4-4-6 6'
								/>
							</svg>
						</div>
						<div>
							<h3 className='font-bold text-xl'>+10</h3>
							<p>Available Solutions</p>
						</div>
					</div>
				</div>
			</section>

			<div class='bg-white py-6 sm:py-8 lg:py-12'>
				<div class='max-w-screen-2xl px-4 md:px-8 mx-auto'>
					<div class='mb-10 md:mb-16'>
						<h2 class='text-gray-800 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-6'>
							Frequently asked questions
						</h2>

						<p class='max-w-screen-md text-gray-500 md:text-lg text-center mx-auto'>
							This is a section of some simple filler text, also known as
							placeholder text. It shares some characteristics of a real written
							text but is random or otherwise generated.
						</p>
					</div>

					<div class='grid sm:grid-cols-2 xl:grid-cols-3 gap-8 sm:gap-y-10'>
						<div class='bg-gray-100 rounded-lg relative p-5 pt-8'>
							<span class='w-8 h-8 inline-flex justify-center items-center bg-indigo-500 text-white rounded-full absolute -top-4 left-4'>
								<svg
									xmlns='http://www.w3.org/2000/svg'
									class='w-5 h-5'
									viewBox='0 0 20 20'
									fill='currentColor'
								>
									<path
										fill-rule='evenodd'
										d='M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z'
										clip-rule='evenodd'
									/>
								</svg>
							</span>

							<h3 class='text-indigo-500 text-lg md:text-xl font-semibold mb-3'>
								what is internet of things?
							</h3>
							<p class='text-gray-500'>
								The Internet of Things (IoT) is the network of physical
								objects—devices, vehicles, buildings and other items embedded
								with electronics, software, sensors, and connectivity which
								enables these objects to collect and exchange data.
							</p>
						</div>

						<div class='bg-gray-100 rounded-lg relative p-5 pt-8'>
							<span class='w-8 h-8 inline-flex justify-center items-center bg-indigo-500 text-white rounded-full absolute -top-4 left-4'>
								<svg
									xmlns='http://www.w3.org/2000/svg'
									class='w-5 h-5'
									viewBox='0 0 20 20'
									fill='currentColor'
								>
									<path
										fill-rule='evenodd'
										d='M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z'
										clip-rule='evenodd'
									/>
								</svg>
							</span>

							<h3 class='text-indigo-500 text-lg md:text-xl font-semibold mb-3'>
								What are the features?
							</h3>
							<p class='text-gray-500'>
								IoT allows for connected devices to collect and exchange data,
								monitor and control remotely, improve automation and efficiency
								through real-time data analysis and smart environments.
							</p>
						</div>

						<div class='bg-gray-100 rounded-lg relative p-5 pt-8'>
							<span class='w-8 h-8 inline-flex justify-center items-center bg-indigo-500 text-white rounded-full absolute -top-4 left-4'>
								<svg
									xmlns='http://www.w3.org/2000/svg'
									class='w-5 h-5'
									viewBox='0 0 20 20'
									fill='currentColor'
								>
									<path
										fill-rule='evenodd'
										d='M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z'
										clip-rule='evenodd'
									/>
								</svg>
							</span>

							<h3 class='text-indigo-500 text-lg md:text-xl font-semibold mb-3'>
								What about integrations?
							</h3>
							<p class='text-gray-500'>
								IoT integration with technologies like cloud, AI, and analytics,
								enables advanced capabilities like predictive maintenance,
								improved security and more sophisticated decision-making.
							</p>
						</div>

						<div class='bg-gray-100 rounded-lg relative p-5 pt-8'>
							<span class='w-8 h-8 inline-flex justify-center items-center bg-indigo-500 text-white rounded-full absolute -top-4 left-4'>
								<svg
									xmlns='http://www.w3.org/2000/svg'
									class='w-5 h-5'
									viewBox='0 0 20 20'
									fill='currentColor'
								>
									<path
										fill-rule='evenodd'
										d='M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z'
										clip-rule='evenodd'
									/>
								</svg>
							</span>

							<h3 class='text-indigo-500 text-lg md:text-xl font-semibold mb-3'>
								Is support available?
							</h3>
							<p class='text-gray-500'>
								Support is available, our team is ready to assist you with any
								questions or issues you may have. We offer various channels for
								support such as phone, email, live chat, and self-help
								resources.
							</p>
						</div>

						<div class='bg-gray-100 rounded-lg relative p-5 pt-8'>
							<span class='w-8 h-8 inline-flex justify-center items-center bg-indigo-500 text-white rounded-full absolute -top-4 left-4'>
								<svg
									xmlns='http://www.w3.org/2000/svg'
									class='w-5 h-5'
									viewBox='0 0 20 20'
									fill='currentColor'
								>
									<path
										fill-rule='evenodd'
										d='M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z'
										clip-rule='evenodd'
									/>
								</svg>
							</span>

							<h3 class='text-indigo-500 text-lg md:text-xl font-semibold mb-3'>
								What is the pricing?
							</h3>
							<p class='text-gray-500'>
								Pricing varies depending on the product or service, we offer
								options to suit different budgets. Contact our sales team for a
								quote based on your specific needs.
							</p>
						</div>

						<div class='bg-gray-100 rounded-lg relative p-5 pt-8'>
							<span class='w-8 h-8 inline-flex justify-center items-center bg-indigo-500 text-white rounded-full absolute -top-4 left-4'>
								<svg
									xmlns='http://www.w3.org/2000/svg'
									class='w-5 h-5'
									viewBox='0 0 20 20'
									fill='currentColor'
								>
									<path
										fill-rule='evenodd'
										d='M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z'
										clip-rule='evenodd'
									/>
								</svg>
							</span>

							<h3 class='text-indigo-500 text-lg md:text-xl font-semibold mb-3'>
								Is IoT dangerous?
							</h3>
							<p class='text-gray-500'>
								IoT can bring benefits but also poses security risks like
								unauthorized access, hacking and malware. It&apos;s important to
								secure IoT devices and networks to protect against these risks,
								by using strong passwords, keeping software and firmware up to
								date, and using encryption to protect data.
							</p>
						</div>
					</div>
				</div>
			</div>

			<div class='flex flex-col items-center bg-gray-100 rounded-lg p-4 sm:p-8'>
				<div class='mb-4 sm:mb-8'>
					<h2 class='text-indigo-500 text-xl sm:text-2xl lg:text-3xl font-bold text-center'>
						Get the latest updates
					</h2>
					<p class='text-gray-500 text-center'>Sign up for our newsletter</p>
				</div>

				<form class='w-full max-w-md flex gap-2 mb-3 sm:mb-5'>
					<input
						placeholder='Email'
						class='w-full flex-1 bg-gray-white text-gray-800 placeholder-gray-400 border border-gray-300 focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2'
					/>

					<button class='inline-block bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 focus-visible:ring ring-indigo-300 text-white text-sm md:text-base font-semibold text-center rounded outline-none transition duration-100 px-8 py-2'>
						Send
					</button>
				</form>

				<p class='text-gray-400 text-xs text-center'>
					By signing up to our newsletter you agree to our{' '}
					<a
						href='#'
						class='hover:text-indigo-500 active:text-indigo-600 underline transition duration-100'
					>
						Term of Service
					</a>{' '}
					and{' '}
					<a
						href='#'
						class='hover:text-indigo-500 active:text-indigo-600 underline transition duration-100'
					>
						Privacy Policy
					</a>
					.
				</p>
			</div>
			<div class='bg-white pt-4 sm:pt-10 lg:pt-12'>
				<footer class='max-w-screen-2xl px-4 md:px-8 mx-auto'>
					<div class='grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 border-t gap-12 lg:gap-8 pt-10 lg:pt-12 mb-16'>
						<div class='col-span-full lg:col-span-2'>
							<div class='lg:-mt-2 mb-4'>
								<Link
									href='/'
									class='inline-flex items-center text-black-800 text-xl md:text-2xl font-bold gap-2'
									aria-label='logo'
								>
									<svg
										width='95'
										height='94'
										viewBox='0 0 95 94'
										class='w-5 h-auto text-indigo-500'
										fill='currentColor'
										xmlns='http://www.w3.org/2000/svg'
									>
										<path d='M96 0V47L48 94H0V47L48 0H96Z' />
									</svg>
									Enhanced
								</Link>
							</div>

							<p class='text-gray-500 sm:pr-8 mb-6'>
								Tech Startup specialized in Internet of Things and Revolutions.
							</p>

							<div class='flex gap-4'>
								<a
									href='#'
									target='_blank'
									class='text-gray-400 hover:text-gray-500 active:text-gray-600 transition duration-100'
								>
									<svg
										class='w-5 h-5'
										width='24'
										height='24'
										viewBox='0 0 24 24'
										fill='currentColor'
										xmlns='http://www.w3.org/2000/svg'
									>
										<path d='M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z' />
									</svg>
								</a>

								<a
									href='#'
									target='_blank'
									class='text-gray-400 hover:text-gray-500 active:text-gray-600 transition duration-100'
								>
									<svg
										class='w-5 h-5'
										width='24'
										height='24'
										viewBox='0 0 24 24'
										fill='currentColor'
										xmlns='http://www.w3.org/2000/svg'
									>
										<path d='M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z' />
									</svg>
								</a>

								<a
									href='#'
									target='_blank'
									class='text-gray-400 hover:text-gray-500 active:text-gray-600 transition duration-100'
								>
									<svg
										class='w-5 h-5'
										width='24'
										height='24'
										viewBox='0 0 24 24'
										fill='currentColor'
										xmlns='http://www.w3.org/2000/svg'
									>
										<path d='M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z' />
									</svg>
								</a>

								<a
									href='#'
									target='_blank'
									class='text-gray-400 hover:text-gray-500 active:text-gray-600 transition duration-100'
								>
									<svg
										class='w-5 h-5'
										width='24'
										height='24'
										viewBox='0 0 24 24'
										fill='currentColor'
										xmlns='http://www.w3.org/2000/svg'
									>
										<path d='M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z' />
									</svg>
								</a>
							</div>
						</div>

						<div>
							<div class='text-gray-800 font-bold tracking-widest uppercase mb-4'>
								Products
							</div>

							<nav class='flex flex-col gap-4'>
								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Overview
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Solutions
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Pricing
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Customers
									</a>
								</div>
							</nav>
						</div>

						<div>
							<div class='text-gray-800 font-bold tracking-widest uppercase mb-4'>
								Company
							</div>

							<nav class='flex flex-col gap-4'>
								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										About
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Investor Relations
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Jobs
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Press
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Blog
									</a>
								</div>
							</nav>
						</div>

						<div>
							<div class='text-gray-800 font-bold tracking-widest uppercase mb-4'>
								Support
							</div>

							<nav class='flex flex-col gap-4'>
								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Contact
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Documentation
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Chat
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										FAQ
									</a>
								</div>
							</nav>
						</div>

						<div>
							<div class='text-gray-800 font-bold tracking-widest uppercase mb-4'>
								Legal
							</div>

							<nav class='flex flex-col gap-4'>
								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Terms of Service
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Privacy Policy
									</a>
								</div>

								<div>
									<a
										href='#'
										class='text-gray-500 hover:text-indigo-500 active:text-indigo-600 transition duration-100'
									>
										Cookie settings
									</a>
								</div>
							</nav>
						</div>
					</div>

					<div class='text-gray-400 text-sm text-center border-t py-8'>
						© 2021 - Present Enhanced. All rights reserved.
					</div>
				</footer>
			</div>
		</>
	);
}
